// planes tickets
export const REQUESTED_TICKETS = "REQUESTED_TICKETS";
export const FETCHED_TICKET = "FETCHED_TICKET";
export const REQUESTED_TICKETS_SUCCEEDED = "REQUESTED_TICKETS_SUCCEEDED";
export const REQUESTED_TICKETS_FAILED = "REQUESTED_TICKETS_FAILED";
export const ADD_CURRENT_TICKET = "ADD_CURRENT_TICKET";

export const SIGN_IN = "SIGN_IN";
export const LOG_OUT = "LOG_OUT";
export const GET_USER = "GET_USER";
export const FETCHED_USER = "FETCHED_USER";
export const REQUESTED_USER = "REQUESTED_USER";
export const REQUESTED_USER_SUCCEEDED = "REQUESTED_USER_SUCCEEDED";
export const REQUESTED_USER_FAILED = "REQUESTED_USER_FAILED";
export const ADD_PARAMETERS_OF_SEARCHING = "ADD_PARAMETERS_OF_SEARCHING";
export const PAY_TICKETS = "PAY_TICKETS";
